// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbmibcpmxdzkatnmtrkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxibWliY3BteGR6a2F0bm10cmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTQ5NzMsImV4cCI6MjA2MTEzMDk3M30.RSMBL2gVCVwIO7P6QBleySX1TKBE7IRDeHi9xhxj4zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);